export { TabNavigationNew } from './TabNavigationNew';
export { SeguimientoTab } from './SeguimientoTab';
export { SemaforoTabNew } from './SemaforoTabNew';
export { PrediccionesTab } from './PrediccionesTab';
export { ReporteIATab } from './ReporteIATab';
export { AsistenteTab } from './AsistenteTab';
export { MLSystemTab } from './MLSystemTab';
export { default as FlashTab } from './FlashTab';
export { default as DemandTab } from './DemandTab';
export { default as GamificationTab } from './GamificationTab';
export { ProcesosLitperTab } from './ProcesosLitperTab';
export { CiudadAgentesTab } from './CiudadAgentesTab';
export { AprendizajeIATab } from './AprendizajeIATab';
export { DistritosIATab } from './DistritosIATab';
export { MCPConnectionsTab } from './MCPConnectionsTab';
export { ConexionesTab } from './ConexionesTab';
